#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACM)
if [ -n "$FILES" ]
then
    dotnet format PocketClient.sln --include $FILES --exclude "PocketClient.Core/Data/Migrations/*.cs" --verify-no-changes --verbosity n
fi